### ISSUE TITLE
Number of players reading

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#11]
https://github.com/samadio/SDM_exam/blob/game_dev/src/main/java/dotsandboxes/DotsAndBoxesInput.java#L111

Questa linea fa si che il programma rimanga in attesa di nuovo input usando System.in. Commentata  per far funzionare il programma e verificarne il funzionamento. Andrebbe rivista e migliorata.

**Comment by samadio** [comment]
Dalla documentazione
1.Java Scanner hasNext () Method:

It is a Scanner class method which returns true if this scanner has another token in its input. This method may block while waiting for input to scan.

Ora vedo se trovo soluzioni migliori, anche se non capisco da come e' scritto se questo behaviour sia un bug o per qualche motivo voluto

**Comment by federico-camerota** [comment]
Direi che è voluto. Il senso è quello di aspettare fino a che la sorgente ha nuovo input oppure viene segnalato che non c'è più input con un EOF o simili (Ctrl+d su terminale). Ovviamente la cosa dovrebbe valere solo per sorgenti tipo System.in in cui vi è la possibilità di nuovo input su richiesta. Nel caso di un file o di una stringa invece dovrebbe restiture false se l'input è terminato.

**Comment by samadio** [comment]
Soluzione proposta (non testata compilando, come idea):

Scanner s= new Scanner();

//s.tokens() returns Stream of tokens from input separated by default sep " "
if(s.tokens().count()==1) return s.tokens().map(x->Integer.valueOf(x)).sum();
throw Error

**Comment by federico-camerota** [comment]
Direi che può andare

**Comment by samadio** [comment]
Dimenticavo che sum giustamente si applica su un IntStream

all the same except

return s.tokens().mapToInt(x->Integer.valueOf(x)).sum();

**Comment by samadio** [comment]
visto che s.tokens() per qualche motivo consuma lo scanner originario, ho cambiato approccio:
prima costuisco la List<String> input=s.tokens().collect(Collectors::toList<String>).
Poi controllo size e lavoro con input. Vedi codice.
Aspetto conferma per chiudere l'issue

**Comment by federico-camerota** [comment]
Visto che tokens consuma lo scanner suggerirei di arrivare alla lista usando Arrays.toList(s.nextLine().split()). Non è funzionale ma elimina il problema. Credo comunque lo scanner in questo caso continui a funzionare anche dopo aver chiamato tokens perchè legato a System.in

**Comment by samadio** [comment]
dovrei aver risolto tutto. ho provato anche il behaviour delle eccezioni e gia' che c'ero ho fatto si che gli elementi vuoti in una lista non ci diano problemi(quindi un input="       4"    oppure "4      "  vengano ragionevolmente considerati validi). Confermami che chiudo

**Comment by federico-camerota** [comment]
L'idea andava bene, ho apportato un paio di semplici modifiche:
- Arrays.asList restituisce già una lista quindi inutile creare un ArrayList visto che non abbiamo bisogno di sapere il tipo specifico di lista.
- Siccome ci interessa unicamente rimuovere gli spazi all'inizio della stringa usare il metodo trim() penso sia più chiaro, conciso e (probabilmente) efficiente.
