### ISSUE TITLE
Esaurimento sorgente input

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#17]
https://github.com/samadio/SDM_exam/blob/simone/src/main/java/dotsandboxes/io/DotsAndBoxesInput.java#L62

La gestione di questa situazione dovrà essere spostata fuori dall' InputManager

**Comment by samadio** [comment]
Ho creato una nuova classe che si occupi di cercare le exit/reset keywords e lanciare le eccezioni e ho spostato le classi ausiliare di InpuManager in un file diverso per leggibilita'.

Fammi sapere se la cosa ti garba

**Comment by federico-camerota** [comment]
Quello che hai fatto direi che va bene. Ma il problema a cui mi riferivo in questo issue rimane (da quel che vedo almeno).

**Comment by samadio** [comment]
allora forse non ho capito cosa intendi nell'issue. La riga 62 e' quella della classe per exit/reset keywords. Quale situazioni vorresti spostare fuori dall'input manager?

**Comment by federico-camerota** [comment]
La situazione in cui lo scanner raggiunge la fine del file, nel caso di System.in quando tu premi Ctrl+D. In questo momento quello che succede è che il programma termina ma per via di una exception non gestita (proprio perchè lo scanner non ha più un next element)

**Comment by samadio** [comment]
aaaaah ok penso la riga sia cambiata nel corso del codice, per quello vedevo male

**Comment by federico-camerota** [comment]
https://github.com/samadio/SDM_exam/blob/3bb3f607d3416383fb220d963016727cff8a5047/src/main/java/dotsandboxes/io/DotsAndBoxesInput.java#L33

**Comment by federico-camerota** [comment]
Questa è la riga di cui parlavo, effettivamente ha cambiato numero nel frattempo
