### ISSUE TITLE
is this violation of single responsability principle?

### ISSUE THREAD

**Issue by samadio** [samadio/SDM_exam#20]
https://github.com/samadio/SDM_exam/blob/651894ff8f3f3970e9995c61c802c9eea1be44ec/src/main/java/dotsandboxes/io/DotsAndBoxesInput.java#L111

il metodo getGridDimension non solo ottiene le dimensioni della griglia ma le usa anche per inizializzare il converter

**Comment by federico-camerota** [comment]
Si può anche togliere. Semplicemente sembrava comodo per non dover prima leggere le dimensioni e poi settare il converter esteranamente. Ma efettivamente potrebbe rendere il design più pulito se la lettura delle dimensioni non lega il converter a quelle dimensioni.

**Comment by federico-camerota** [comment]
Tuttavia, per come scritto al momento il codice in GameSetter è necessario che getGridDimensions setti anche il converter poichè il converter è un qualcosa che abbiamo lasciato come proprio del nostro D&B game quindi nelle classi astratte non è contemplato.
