### ISSUE TITLE
default numero di players?

### ISSUE THREAD

**Issue by samadio** [samadio/SDM_exam#21]
https://github.com/samadio/SDM_exam/blob/3bb3f607d3416383fb220d963016727cff8a5047/src/main/java/dotsandboxes/io/DotsAndBoxesInput.java#L111

i=2 viene mai usato come default value? se la risposta mi confermi essere no, lo toglierei

**Comment by federico-camerota** [comment]
Nope, non viene usato.

**Comment by federico-camerota** [comment]
Tuttavia, togliendolo non compila.

**Comment by samadio** [comment]
togliendolo intendi lasciando solo
int i;
vero?

**Comment by samadio** [comment]
A sto punto ti direi di lasciare un default negativo/0, cosi nel caso effettivamente per qualche magia la variabile non venga sovrascritta dall'input, il gioco riprovi a settarla piuttosto che andare avanti con un numero di giocatori diverso da quello scelto

**Comment by federico-camerota** [comment]
Mi sembra una buona soluzione
