### ISSUE TITLE
backgroundPanelInit method is doing more than that

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#27]
https://github.com/samadio/SDM_exam/blob/733971a300e44a55a053cee5d826ac5758081ba5/src/main/java/dotsandboxes/gui/DotsAndBoxesGui.java#L31

Questo metodo non sta facendo unicamente l'inizializzazione del BackgroundPanel ma sta anche andando a settare parametri del JFrame. Probabilmente tali operazioni andrebbero spostate nel costruttore subito dopo la chiamata a questo metodo.
(Se necessario chiamare il metodo add di JFrame dopo aver eseguito tale settaggio si può risolvere la questione facendo restituire al metodo il BackgroundPanel creato)

**Comment by andygaspar** [comment]
vero, questo è da sistemare ancora. Ma devo farci una pensata, forse si può spostare tutto nel costruttore della gui
