### ISSUE TITLE
setFrame method is doing lots of stuff

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#29]
https://github.com/samadio/SDM_exam/blob/733971a300e44a55a053cee5d826ac5758081ba5/src/main/java/dotsandboxes/gui/frames/GridFrame.java#L21

Il metodo setFrame sta facendo molte cose, tra queste impostare l'aspetto del frame e poi leggere dell'input. Va decisamente rivista questa cosa, dividendola in varie parti. Ciò che riguarda l'impostazione del frame stesso ritengo vada spostato nel costruttore (magari chiamando un metodo che faccia ciò ma comunque come parte del processo di costruzione del frame). 
Il metodo setFrame, per come usato dovrebbe quindi solamente occuparsi della lettura e restituzione dell'input.

**Comment by andygaspar** [comment]
spostato tutto nel costruttore come fatto notare giustamente da te.
setframe è diventato getInput e fa solo quello
