### ISSUE TITLE
startGame method

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#30]
https://github.com/samadio/SDM_exam/blob/7d0368a06faf81ba5b4e3893e1af86645a512d92/src/main/java/iomanagement/OutputManager.java#L12

In questo metodo vedo i seguenti problemi:

-Il nome risulta leggermente fuorviante, la mia prima reazione è stata "perchè l'output manager dovrebbe iniziare il gioco?". 

-Nella versione del gioco da riga di comando mi sembra di capire il metodo sia usato per stampare un messaggio iniziale, la cosa può andar bene ma cambierei il nome in qualcosa tipo showInitialMessage. (In questo caso il metodo potrebbe servire uno scopo importante nella user experience, apro ulteriore issue). Invece nel caso della gui il metodo sta svolgendo un ruolo diverso, inizializzando un membro. Ciò mi sembra più adeguato alla fase di costruzione del JFrame, a questo punto il metodo potrebbe semplicemente rendere visibile il gameFrame, il che corrisponde grosso modo al ruolo ricoperto dal metodo nell'altra versione del gioco.

**Comment by andygaspar** [comment]
concordo, il metodo serve ad inizializzare il frame. Si può decidere di cambiare nome e fare stampare anche la board nella versione rdc.
I costruttori sono stati tutti sistemati come richiesto
