### ISSUE TITLE
Access specifiers and public members

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#32]
Ho notato in molte classi (specialmente quelle legate ai frame) l'uso di membri publici che vengono poi modificati da altre classi. Ritengo questo approccio poco adeguato poichè rende il codice difficile da mantenere pulito ed efficente nel tempo  siccome gli utilizzatori della classe hanno accesso alla struttura interna e sono legati a nomi specifici forniti ai membri. Ipotizzando di voler fare del refactoring per migliorare il design o l'efficienza della classe bisognerebbe andare a ritoccare anche tutto il codice che sfrutta questi membri. Inoltre, se si volessero aggiungere funzionalità/vincoli o altri passaggi intermedi di qualsivoglia natura, nelle operazioni che al momento vengono eseguite accedendo direttamente ai membri, ciò non è possibile nel presente schema. 

Suggerisco quindi di rivedere questi utilizzi e dove possible passare a membri privati che vengono letti/scritti tramite metodi getter e setter rendendo più chiara e snella l'interfaccia pubblica della classe stessa.

**Comment by andygaspar** [comment]
Concordissimo, provvedo appena ho due minuti

**Comment by andygaspar** [comment]
Fatto
