### ISSUE TITLE
Should a Frame exist?

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#35]
https://github.com/samadio/SDM_exam/blob/362756c0c1a82ff74a41ff08e2c515d56ea8251b/src/main/java/dotsandboxes/gui/frames/Frame.java#L5

Mi sembra di capire che la classe Frame fornisca unicamente dei metodi comuni a tutte le sottoclassi derivate. Intendo dire, ha ragion d'essere un'istanza della classe Frame? O soltanto istanze delle sue sottoclassi sono ragionevoli? Poichè mi sembra che la situazione attuale sia la seconda, proporrei di trasformare frame in una classe astratta in modo tale da impedire la creazione di istanze di quest'ultima e mantenere il design desiderato.

**Comment by andygaspar** [comment]
Lo pensavo e ce lo siamo detti al telefono
Lo hai già sistemato
Tutto benissimo top top top
Quindi chiudo l'issue
