### ISSUE TITLE
Incorrect usage of Swing components

### ISSUE THREAD

**Issue by federico-camerota** [samadio/SDM_exam#37]
https://github.com/samadio/SDM_exam/blob/1d7524a982879674b411724ea1dd0afe31738790/src/main/java/dotsandboxes/gui/graphics/DBLabel.java#L5

Come nel caso della classe DBButton molti dei membri sono repliche di membri che le classi da cui si eredita già possiedono e per i queli ci sono metodi setter / getter. Anche nel caso di DBLabel (ed immagino anche in altre classi a questo punto) andrebbe fatto del refactoring come per DBButton per eliminare tutta questa ridondanza ed usare ciò che già viene predisposto dai componenti della libreria.

**Comment by andygaspar** [comment]
Quello è esattamente il punto più critico. La necessità l'ho vista già da subito. Il come fare ancora non lo so
