### ISSUE TITLE
metodi privati e test

### ISSUE THREAD

**Issue by samadio** [samadio/SDM_exam#47]
https://github.com/samadio/SDM_exam/blob/13d72c6b0cce880694233b37ffc461b69da07ab6/src/main/java/dotsandboxes/io/DotsAndBoxesInput.java#L46

    public InputMove readInputMove() throws DataFormatException

In questo caso, e non penso sia l'unico, abbiamo un metodo che e' pubblico solo per permetterne i test. Arrivati a questo punto lo metto privato e per fare il test uso il metodo pubblico che chiama readInputMove. Datemi conferma

**Comment by samadio** [comment]
Oppure spiegatemi perche' potrebbe essere utile avere un readInputMove pubblico per poter usare la Move in modo "slegato" dal resto dell'architettura. Magari mi sfugge

**Comment by federico-camerota** [comment]
Direi di sì, InputMove è una è una rappresentazione interna usata dal manager quindi per come organizzato il tutto non vedo ragione di ottenerla dall'esterno. Probabilmente è rimasta public causa i test
